### ISSUE TITLE
加油，与此同时也很担心

### ISSUE THREAD

**Issue by wanghao1993** [SHSSEDU/shssedu.github.io#18]
996 ICU的成员已经进去了，3-5年不等，组织意味信仰，信仰意味力量，在我的国信仰是不被允许的存在，如果允许，只能有一种。

**Comment by WeileiZeng** [comment]
敏感话题确实比较敏感，但这个项目有很多发展方向，其创意和愿景是很好的，不一定非要通过敏感激进的方式来表达。目前还可以观望一下。
